/* This ANTLR4 grammar has been generated by Poirot */

grammar msg_exec;

axiom : s EOF;
exe : 'e' 'x' 'e' 'c' ' ' 'c' 'm' 'd';
msg : 'm' 's' 'g' ' ' params;
params : 'k' 'e' 'y' ' ' '=' ' ' 'v' 'a' 'l' 'u' 'e' | 'k' 'e' 'y' ' ' '=' ' ' 'v' 'a' 'l' 'u' 'e' ' ' '&' ' ' params;
s : exe | exe ' ' ';' ' ' s | msg | msg ' ' ';' ' ' s;
