S;
S ::= Select;
String ::= "'<str>'";
Int ::= "<int>";
Name ::= "<name>";
Select ::= "select" Names "from" Name Where Union;
Select ::= "select" Vals;
Names ::= All;
Names ::= NamesBis;
NamesBis ::= Name;
NamesBis ::= Name "," NamesBis;
All ::= "<etoile>";
Where ::= ;
Where ::= "where" Conds;
Op ::= "and";
Op ::= "or";
Cond ::= "<int>";
Cond ::= Name "=" Val;
Cond ::= Val "=" Val;
Conds ::= Cond;
Conds ::= Cond Op Conds;
Val ::= Int;
Val ::= String;
Vals ::= Val "," Vals;
Vals ::= Val;
Union ::= ;
Union ::= "union" Select;
